unit PModExport;

(*
   Module's exported routines unit
   This code is generated by EASY DAF 2.0i
   Please do not modify directly
*)

interface

uses PModClsDecl, KernelIntf, ImplTab;

procedure PObjDLLInit(ASysConfig: ISysConfig); stdcall;
procedure PObjDLLInit2(AModuleHandle: Integer); stdcall;
function PObjDLLCanUnload(): boolean; stdcall;
function PObjDLLGetPClassImpl(APClassName: string): IPClassImpl; stdcall;
procedure PObjDLLFinalize; stdcall;

exports
  PObjDLLInit,
  PObjDLLInit2,
  PObjDLLCanUnload,
  PObjDLLGetPClassImpl,
  PObjDLLFinalize;

implementation

procedure PObjDLLInit(ASysConfig: ISysConfig);
begin
  Register_PClassVariables(ASysConfig);
end;

procedure PObjDLLInit2(AModuleHandle: Integer);
begin
  DefImplTab.SetModuleHandle(AModuleHandle);
end;

function PObjDLLCanUnload(): boolean;
begin
  Result := DefImplTab.AllPClsAreFree;
end;

function PObjDLLGetPClassImpl(APClassName: string): IPClassImpl;
var ImplTabEntry: TImplTabElmt;
begin
  ImplTabEntry := DefImplTab.ElementByName[APClassName];
  if ImplTabEntry <> nil then
    Result := ImplTabEntry.PClassImpl
  else
    Result := nil;
end;

procedure PObjDLLFinalize;
begin
  DefImplTab.Reset;
  PModClsDecl.UnRegister_PClassVariables;
end;

end.
