unit PModClsDecl;

(*
   Module's PClass declaration unit
   This code is generated by EASY DAF 2.0i
   Please do not modify directly

   All class type variables are registered here
*)

interface

uses ModUserMgmt, KernelIntf;

procedure Register_PClassVariables(AConfig: ISysConfig);
procedure UnRegister_PClassVariables;

var
  PCls_BranchLocation: IPClassImpl;
  PCls_UserApp: IPClassImpl;
  PCls_UserGroup: IPClassImpl;
  PCls_UserGroupApp: IPClassImpl;

implementation

procedure Register_PClassVariables(AConfig: ISysConfig);
begin
  PCls_BranchLocation := TPCls_BranchLocation.Create(AConfig, 'BranchLocation');
  PCls_UserApp := TPCls_UserApp.Create(AConfig, 'UserApp');
  PCls_UserGroup := TPCls_UserGroup.Create(AConfig, 'UserGroup');
  PCls_UserGroupApp := TPCls_UserGroupApp.Create(AConfig, 'UserGroupApp');
end;

procedure UnRegister_PClassVariables;
begin
  PCls_BranchLocation := nil;
  PCls_UserApp := nil;
  PCls_UserGroup := nil;
  PCls_UserGroupApp := nil;
end;

initialization

end.
