-- Enumeration check for class AhliWaris
SELECT * FROM AHLIWARIS WHERE (
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL OR 
(STATUS_AHLI_WARIS NOT IN (A, N) AND STATUS_AHLI_WARIS IS NOT NULL OR 
(HUBUNGAN_KELUARGA NOT IN (0, 1, 2, 3, 4, 5, 6, 7, 8) AND HUBUNGAN_KELUARGA IS NOT NULL
);

-- Enumeration check for class BiayaAdmTransaksi
SELECT * FROM TRANSAKSIDPLK WHERE KODE_JENIS_TRANSAKSI = 'X' AND (
(ISPINDAHPAKET NOT IN (F, T) AND ISPINDAHPAKET IS NOT NULL
);

-- Enumeration check for class blobregistration
SELECT * FROM BLOBREGISTRATION WHERE (
(ISTEMPORARY NOT IN (F, T) AND ISTEMPORARY IS NOT NULL
);

-- Enumeration check for class BranchLocation
SELECT * FROM BRANCHLOCATION WHERE (
(BranchStatus NOT IN (B, S) AND BranchStatus IS NOT NULL OR 
(BRANCH_TIME_ZONE NOT IN (B, T, TA) AND BRANCH_TIME_ZONE IS NOT NULL
);

-- Enumeration check for class CustodianBank
SELECT * FROM CUSTODIANBANK WHERE (
(JENIS NOT IN (U, R, M) AND JENIS IS NOT NULL OR 
(KANTOR NOT IN (C, K, P) AND KANTOR IS NOT NULL
);

-- Enumeration check for class Deposito
SELECT * FROM DEPOSITO WHERE (
(ARO NOT IN (F, T) AND ARO IS NOT NULL OR 
(KAPITALISIR_ROLLOVER NOT IN (F, T) AND KAPITALISIR_ROLLOVER IS NOT NULL OR 
(JENISJATUHTEMPO NOT IN (1, 3, 6, 12, 0) AND JENISJATUHTEMPO IS NOT NULL OR 
(TREATMENTPOKOK NOT IN (A, K, P) AND TREATMENTPOKOK IS NOT NULL
);

-- Enumeration check for class HistoriAhliWarisDetail
SELECT * FROM HISTORIAHLIWARISDETAIL WHERE (
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL OR 
(STATUS_AHLI_WARIS NOT IN (A, N) AND STATUS_AHLI_WARIS IS NOT NULL OR 
(HUBUNGAN_KELUARGA NOT IN (0, 1, 2, 3, 4, 5, 6, 7, 8) AND HUBUNGAN_KELUARGA IS NOT NULL
);

-- Enumeration check for class HistoriGiro
SELECT * FROM HISTORIGIRO WHERE (
(ISTRANSAKSICREATED NOT IN (F, T) AND ISTRANSAKSICREATED IS NOT NULL
);

-- Enumeration check for class HistoriGiroHarian
SELECT * FROM HISTORIGIROHARIAN WHERE (
(ISRECONCILED NOT IN (F, T) AND ISRECONCILED IS NOT NULL OR 
(ISTRANSACTIONPROCEED NOT IN (F, T) AND ISTRANSACTIONPROCEED IS NOT NULL
);

-- Enumeration check for class HistoriUbahAlamat
SELECT * FROM HISTORIUBAHALAMAT WHERE (
(KIRIM_STATEMEN NOT IN (N, R, K) AND KIRIM_STATEMEN IS NOT NULL
);

-- Enumeration check for class HistoriUbahStatusKerja
SELECT * FROM HISTORIUBAHSTATUSKERJA WHERE (
(JENIS_TRANSAKSI NOT IN (R, O) AND JENIS_TRANSAKSI IS NOT NULL
);

-- Enumeration check for class HistPerubahanDeposito
SELECT * FROM HISTPERUBAHANDEPOSITO WHERE (
(TREATMENTPOKOKAWAL NOT IN (A, K, P) AND TREATMENTPOKOKAWAL IS NOT NULL OR 
(TREATMENTPOKOKPRB NOT IN (A, K, P) AND TREATMENTPOKOKPRB IS NOT NULL OR 
(ISKAPITALISIRAWAL NOT IN (F, T) AND ISKAPITALISIRAWAL IS NOT NULL OR 
(ISKAPITALISIRPRB NOT IN (F, T) AND ISKAPITALISIRPRB IS NOT NULL OR 
(JENISJATUHTEMPOAWAL NOT IN (1, 3, 6, 12, 0) AND JENISJATUHTEMPOAWAL IS NOT NULL OR 
(JENISJATUHTEMPOPRB NOT IN (1, 3, 6, 12, 0) AND JENISJATUHTEMPOPRB IS NOT NULL OR 
(ER_PERB NOT IN (F, T) AND ER_PERB IS NOT NULL
);

-- Enumeration check for class Investasi
SELECT * FROM INVESTASI WHERE (
(STATUS NOT IN (F, T) AND STATUS IS NOT NULL
);

-- Enumeration check for class IuranPendaftaran
SELECT * FROM IURANPENDAFTARAN WHERE (
(ISCOMMITTED NOT IN (F, T) AND ISCOMMITTED IS NOT NULL
);

-- Enumeration check for class JenisPenerimaanManfaat
SELECT * FROM JENISPENERIMAANMANFAAT WHERE (
(kode_jns_manfaat NOT IN (B, D, C, J) AND kode_jns_manfaat IS NOT NULL
);

-- Enumeration check for class JenisRegisterCIF
SELECT * FROM JENISREGISTERCIF WHERE (
(KODE_JENIS_REGISTERCIF NOT IN (A, W, K, U, P, I, N, D, Z) AND KODE_JENIS_REGISTERCIF IS NOT NULL
);

-- Enumeration check for class JenisTransaksiDPLK
SELECT * FROM JENISTRANSAKSIDPLK WHERE (
(kode_jenis_transaksi NOT IN (A, B, C, D, E, F, G, H, I, J, K, X, Z, M, V, W, O, P) AND kode_jenis_transaksi IS NOT NULL
);

-- Enumeration check for class JnsTransInvestasi
SELECT * FROM JNSTRANSINVESTASI WHERE (
(KODE_JENIS_TRINVESTASI NOT IN (A, C, B, D, F, G, H, I, P, J, L, O, R, S) AND KODE_JENIS_TRINVESTASI IS NOT NULL
);

-- Enumeration check for class LDP
SELECT * FROM LDP WHERE (
(JENIS_DP NOT IN (A, B, C) AND JENIS_DP IS NOT NULL
);

-- Enumeration check for class NasabahDPLK
SELECT * FROM NASABAHDPLK WHERE (
(ISCOMMITTED NOT IN (F, T) AND ISCOMMITTED IS NOT NULL OR 
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL OR 
(ISPESERTAPENGALIHAN NOT IN (F, T) AND ISPESERTAPENGALIHAN IS NOT NULL
);

-- Enumeration check for class NasabahDPLKCorporate
SELECT * FROM NASABAHDPLKCORPORATE WHERE (
(ISCOMMITTED NOT IN (F, T) AND ISCOMMITTED IS NOT NULL
);

-- Enumeration check for class Obligasi
SELECT * FROM OBLIGASI WHERE (
(JENIS_OBLIGASI NOT IN (K, P, N) AND JENIS_OBLIGASI IS NOT NULL OR 
(JENISAKAD NOT IN (I, M, S) AND JENISAKAD IS NOT NULL OR 
(JENISKUPON NOT IN (3, 6, 12, 1) AND JENISKUPON IS NOT NULL OR 
(TREATMENTOBLIGASI NOT IN (H, R) AND TREATMENTOBLIGASI IS NOT NULL
);

-- Enumeration check for class OperationCode
SELECT * FROM OPERATIONCODE WHERE (
(OPERATION_CODE NOT IN (F, E, N) AND OPERATION_CODE IS NOT NULL
);

-- Enumeration check for class PaketInvestasi
SELECT * FROM PAKETINVESTASI WHERE (
(ISAKTIF NOT IN (F, T) AND ISAKTIF IS NOT NULL
);

-- Enumeration check for class PenarikanDana
SELECT * FROM PENARIKANDANA WHERE (
(penarikan_phk NOT IN (F, T) AND penarikan_phk IS NOT NULL OR 
(JENIS_BIAYA NOT IN (T, S, R, P) AND JENIS_BIAYA IS NOT NULL
);

-- Enumeration check for class PenarikanDanaNormal
SELECT * FROM PENARIKANDANA WHERE (
(JENIS_BIAYA NOT IN (T, S, R, P) AND JENIS_BIAYA IS NOT NULL
);

-- Enumeration check for class PenarikanDanaPHK
SELECT * FROM PENARIKANDANA WHERE (
(JENIS_BIAYA NOT IN (T, S, R, P) AND JENIS_BIAYA IS NOT NULL
);

-- Enumeration check for class PengalihanKeDPLKLain
SELECT * FROM PENGALIHANKEDPLKLAIN WHERE (
(JENIS_BIAYA NOT IN (T, S, R, P) AND JENIS_BIAYA IS NOT NULL
);

-- Enumeration check for class PengambilanManfaat
SELECT * FROM PENGAMBILANMANFAAT WHERE (
(JENIS_BIAYA NOT IN (T, S, R, P) AND JENIS_BIAYA IS NOT NULL
);

-- Enumeration check for class PihakKetiga
SELECT * FROM PIHAKKETIGA WHERE (
(SELF_INVESTMENT NOT IN (F, T) AND SELF_INVESTMENT IS NOT NULL OR 
(JENIS NOT IN (U, R, M) AND JENIS IS NOT NULL OR 
(KANTOR NOT IN (C, K, P) AND KANTOR IS NOT NULL
);

-- Enumeration check for class RegEditNasabahRekening
SELECT * FROM REGEDITNASABAHREKENING WHERE (
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL
);

-- Enumeration check for class RegisterAhliWarisDetail
SELECT * FROM REGISTERAHLIWARISDETAIL WHERE (
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL OR 
(STATUS_AHLI_WARIS NOT IN (A, N) AND STATUS_AHLI_WARIS IS NOT NULL OR 
(HUBUNGAN_KELUARGA NOT IN (0, 1, 2, 3, 4, 5, 6, 7, 8) AND HUBUNGAN_KELUARGA IS NOT NULL
);

-- Enumeration check for class RegisterAutoDebet
SELECT * FROM REGISTERAUTODEBET WHERE (
(JENIS_TRANSAKSI NOT IN (R, O) AND JENIS_TRANSAKSI IS NOT NULL
);

-- Enumeration check for class RegisterCIF
SELECT * FROM REGISTERCIF WHERE (
(KODE_JENIS_REGISTERCIF NOT IN (A, W, K, U, P, I, N, D, Z) AND KODE_JENIS_REGISTERCIF IS NOT NULL
);

-- Enumeration check for class RegisterDeposito
SELECT * FROM REGISTERDEPOSITO WHERE (
(ARO NOT IN (F, T) AND ARO IS NOT NULL OR 
(KAPITALISIR_ROLLOVER NOT IN (F, T) AND KAPITALISIR_ROLLOVER IS NOT NULL OR 
(JENISJATUHTEMPO NOT IN (1, 3, 6, 12, 0) AND JENISJATUHTEMPO IS NOT NULL OR 
(TREATMENTPOKOK NOT IN (A, K, P) AND TREATMENTPOKOK IS NOT NULL
);

-- Enumeration check for class RegisterNasabahRekening
SELECT * FROM REGISTERNASABAHREKENING WHERE (
(WASIAT_UMMAT NOT IN (F, T) AND WASIAT_UMMAT IS NOT NULL OR 
(STATUS_BIAYA_DAFTAR NOT IN (F, T) AND STATUS_BIAYA_DAFTAR IS NOT NULL OR 
(KIRIM_STATEMEN NOT IN (N, R, K) AND KIRIM_STATEMEN IS NOT NULL OR 
(AUTO_DEBET NOT IN (F, T) AND AUTO_DEBET IS NOT NULL OR 
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL OR 
(ISREGISTEREDBYADMIN NOT IN (F, T) AND ISREGISTEREDBYADMIN IS NOT NULL OR 
(ISPESERTAPENGALIHAN NOT IN (F, T) AND ISPESERTAPENGALIHAN IS NOT NULL
);

-- Enumeration check for class RegisterObligasi
SELECT * FROM REGISTEROBLIGASI WHERE (
(JENIS_OBLIGASI NOT IN (K, P, N) AND JENIS_OBLIGASI IS NOT NULL OR 
(JENISKUPON NOT IN (3, 6, 12, 1) AND JENISKUPON IS NOT NULL OR 
(JENISAKAD NOT IN (I, M, S) AND JENISAKAD IS NOT NULL OR 
(TREATMENTOBLIGASI NOT IN (H, R) AND TREATMENTOBLIGASI IS NOT NULL
);

-- Enumeration check for class RegisterUbahAlamat
SELECT * FROM REGISTERUBAHALAMAT WHERE (
(KIRIM_STATEMEN NOT IN (N, R, K) AND KIRIM_STATEMEN IS NOT NULL
);

-- Enumeration check for class RegisterUbahStatusKerja
SELECT * FROM REGISTERUBAHSTATUSKERJA WHERE (
(JENIS_TRANSAKSI NOT IN (R, O) AND JENIS_TRANSAKSI IS NOT NULL
);

-- Enumeration check for class RegisterWasiatUmmat
SELECT * FROM REGISTERWASIATUMMAT WHERE (
(JENIS_TRANSAKSI NOT IN (R, O) AND JENIS_TRANSAKSI IS NOT NULL
);

-- Enumeration check for class RegNRAhliWaris
SELECT * FROM REGNRAHLIWARIS WHERE (
(JENIS_KELAMIN NOT IN (P, W) AND JENIS_KELAMIN IS NOT NULL OR 
(STATUS_AHLI_WARIS NOT IN (A, N) AND STATUS_AHLI_WARIS IS NOT NULL OR 
(HUBUNGAN_KELUARGA NOT IN (0, 1, 2, 3, 4, 5, 6, 7, 8) AND HUBUNGAN_KELUARGA IS NOT NULL
);

-- Enumeration check for class RekeningDPLK
SELECT * FROM REKENINGDPLK WHERE (
(STATUS_DPLK NOT IN (A, N, S) AND STATUS_DPLK IS NOT NULL OR 
(STATUS_BIAYA_DAFTAR NOT IN (F, T) AND STATUS_BIAYA_DAFTAR IS NOT NULL OR 
(KIRIM_STATEMEN NOT IN (N, R, K) AND KIRIM_STATEMEN IS NOT NULL OR 
(STATUS_ANUITAS NOT IN (F, T) AND STATUS_ANUITAS IS NOT NULL OR 
(STATUS_AUTODEBET NOT IN (F, T) AND STATUS_AUTODEBET IS NOT NULL OR 
(STATUS_WASIAT_UMMAT NOT IN (F, T) AND STATUS_WASIAT_UMMAT IS NOT NULL OR 
(COLLECTIVITY_WASIAT_UMMAT NOT IN (F, T) AND COLLECTIVITY_WASIAT_UMMAT IS NOT NULL OR 
(IS_BOLEH_DEBET NOT IN (F, T) AND IS_BOLEH_DEBET IS NOT NULL
);

-- Enumeration check for class RolloverDeposito
SELECT * FROM ROLLOVERDEPOSITO WHERE (
(LAKUKAN_KAPITALISIR NOT IN (F, T) AND LAKUKAN_KAPITALISIR IS NOT NULL
);

-- Enumeration check for class SRRCalc
SELECT * FROM SRRCALC WHERE (
(STATUS_BAGIHASIL NOT IN (F, T) AND STATUS_BAGIHASIL IS NOT NULL OR 
(STATUS_REBOND NOT IN (F, T) AND STATUS_REBOND IS NOT NULL
);

-- Enumeration check for class SubJnsTransLRInvestasi
SELECT * FROM SUBJNSTRANSLRINVESTASI WHERE (
(KATEGORI NOT IN (R, L) AND KATEGORI IS NOT NULL
);

-- Enumeration check for class TransactionBatch
SELECT * FROM TRANSACTIONBATCH WHERE (
(BATCH_TYPE NOT IN (R, T, P, I) AND BATCH_TYPE IS NOT NULL OR 
(BATCH_SUB_TYPE NOT IN (M, T) AND BATCH_SUB_TYPE IS NOT NULL OR 
(ACCOUNT_LINK_TYPE NOT IN (S, C) AND ACCOUNT_LINK_TYPE IS NOT NULL OR 
(BATCH_STATUS NOT IN (O, C) AND BATCH_STATUS IS NOT NULL OR 
(IS_POSTED NOT IN (F, T) AND IS_POSTED IS NOT NULL
);

-- Enumeration check for class TransaksiDPLK
SELECT * FROM TRANSAKSIDPLK WHERE (
(ISCOMMITTED NOT IN (F, T) AND ISCOMMITTED IS NOT NULL OR 
(ISPINDAHBUKU NOT IN (F, T) AND ISPINDAHBUKU IS NOT NULL OR 
(TIPE_REKENING_PINDAH_BUKU NOT IN (10, 20) AND TIPE_REKENING_PINDAH_BUKU IS NOT NULL OR 
(FLAG_PILIH NOT IN (F, T) AND FLAG_PILIH IS NOT NULL
);

-- Enumeration check for class TransaksiInvestasi
SELECT * FROM TRANSAKSIINVESTASI WHERE (
(ISCOMMITTED NOT IN (F, T) AND ISCOMMITTED IS NOT NULL OR 
(CLSFTRANSAKSIINVESTASI NOT IN (A, B, C, D, E) AND CLSFTRANSAKSIINVESTASI IS NOT NULL
);

-- Enumeration check for class TransaksiPremi
SELECT * FROM TRANSAKSIPREMI WHERE (
(JENIS_TRANSAKSI NOT IN (T, S, M) AND JENIS_TRANSAKSI IS NOT NULL OR 
(ISCOMMITTED NOT IN (F, T) AND ISCOMMITTED IS NOT NULL OR 
(ISDEBET NOT IN (F, T) AND ISDEBET IS NOT NULL OR 
(ISPINDAHBUKU NOT IN (F, T) AND ISPINDAHBUKU IS NOT NULL OR 
(TIPE_REKENING_PINDAH_BUKU NOT IN (10, 20) AND TIPE_REKENING_PINDAH_BUKU IS NOT NULL
);

-- Enumeration check for class TransLRInvestasi
SELECT * FROM TRANSLRINVESTASI WHERE (
(JENIS NOT IN (K, B, U, H, O, R) AND JENIS IS NOT NULL
);

-- Enumeration check for class TransPiutangInvestasi
SELECT * FROM TRANSPIUTANGINVESTASI WHERE (
(JENIS NOT IN (B, J, S, R, V, T) AND JENIS IS NOT NULL
);

-- Enumeration check for class TutupDeposito
SELECT * FROM TUTUPDEPOSITO WHERE (
(ISPENALTI NOT IN (F, T) AND ISPENALTI IS NOT NULL
);

-- Enumeration check for class UserApp
SELECT * FROM USERAPP WHERE (
(NoLimitLocation NOT IN (F, T) AND NoLimitLocation IS NOT NULL
);

