unit PModClsDecl;

(*
   Module's PClass declaration unit
   This code is generated by EASY DAF 2.0i
   Please do not modify directly

   All class type variables are registered here
*)

interface

uses modBlobRegister, KernelIntf;

procedure Register_PClassVariables(AConfig: ISysConfig);
procedure UnRegister_PClassVariables;

var
  PCls_blobregistration: IPClassImpl;

implementation

procedure Register_PClassVariables(AConfig: ISysConfig);
begin
  PCls_blobregistration := TPCls_blobregistration.Create(AConfig, 'blobregistration');
end;

procedure UnRegister_PClassVariables;
begin
  PCls_blobregistration := nil;
end;

initialization

end.
