  oFile.write('<html>\n')
  oFile.write('\n')
  oFile.write('<head>\n')
  oFile.write('<title>Masa Pensiun</title>\n')
  oFile.write('\n')
  oFile.write('<body style="FONT-FAMILY: Arial; line-height:100%; margin-top:0; margin-bottom:0">\n')
  oFile.write('\n')
  oFile.write('\n')
  oFile.write('<table style="FONT-SIZE: 11; border-collapse: collapse; border-left-width:0; border-right-width:0; border-top-width:0" bordercolor="#111111" border="1" width="100%" id="table1" cellpadding="2">\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td colspan="9" height="20" style="border-left:medium none #000000; border-right:medium none #000000; border-top-style:none; border-top-width:medium; border-bottom-style:none; border-bottom-width:medium">\n')
  oFile.write('		<p align="center"><font size="3" color="#008000"><b>LAPORAN MASA PENSIUN</b></font></td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="100%" colspan="9" style="border-style: none; border-width: medium">\n')
  oFile.write('		<font color="#008000"><b>PERIODE</b></font> <b><font color="#008000">@TGL_AWAL \n')
  oFile.write('		HINGGA @TGL_AKHIR</font></b></td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="5%" align="center" style="border-left:1px solid #000000; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" bgcolor="#CC6699" rowspan="2">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>NO</b></td>\n')
  oFile.write('		<td width="10%" align="center" style="border-style: solid; border-width: 1px; " bgcolor="#CC6699" rowspan="2">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>NO. PESERTA</b></td>\n')
  oFile.write('		<td width="25%" align="center" style="border-style: solid; border-width: 1px; " bgcolor="#CC6699" rowspan="2">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>NAMA LENGKAP</b></td>\n')
  oFile.write('		<td width="10%" align="center" style="border-style: solid; border-width: 1px; " bgcolor="#CC6699">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>TANGGAL</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>LAHIR</b></p>\n')
  oFile.write('		</td>\n')
  oFile.write('		<td width="10%" align="center" style="border-style: solid; border-width: 1px; " bgcolor="#CC6699">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>TANGGAL</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>PENSIUN</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>DIPERCEPAT</b></td>\n')
  oFile.write('		<td width="10%" align="center" style="border-style: solid; border-width: 1px; " bgcolor="#CC6699">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>TANGGAL</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>PENSIUN</b></td>\n')
  oFile.write('		<td width="10%" align="center" style="border-style: solid; border-width: 1px; " bgcolor="#CC6699" rowspan="2">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>AKUMULASI</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>IURAN</b></td>\n')
  oFile.write('		<td width="10%" align="center" style="border-right:1px solid #000000; border-left-style:solid; border-left-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" bgcolor="#CC6699" rowspan="2">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>AKUMULASI</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>PENGALIHAN</b></td>\n')
  oFile.write('		<td width="10%" align="center" style="border-right:1px solid #000000; border-left-style:solid; border-left-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" bgcolor="#CC6699" rowspan="2">\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>AKUMULASI</b></p>\n')
  oFile.write('		<p style="margin-top: 0; margin-bottom: 0"><b>PENGEMBANGAN</b></td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="30%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#CC6699" colspan="3">\n')
  oFile.write('		<p align="center"><b>(DD/MM/YYYY)</b></td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="5%" style="border-left:1px solid #000000; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" bgcolor="#EFEFEF">@no</td>\n')
  oFile.write('		<td width="10%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#EFEFEF">\n')
  oFile.write('		<p align="center">@no_peserta</td>\n')
  oFile.write('		<td width="25%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#EFEFEF">@nama_lengkap</td>\n')
  oFile.write('		<td width="10%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#EFEFEF" align="center">\n')
  oFile.write('		<p align="center">@tgl_lahir</td>\n')
  oFile.write('		<td width="10%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#EFEFEF" align="center">\n')
  oFile.write('		@tgl_dipercepat</td>\n')
  oFile.write('		<td width="10%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#EFEFEF" align="center">\n')
  oFile.write('		@tgl_pensiun</td>\n')
  oFile.write('		<td width="10%" style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px" bgcolor="#EFEFEF">\n')
  oFile.write('		<p align="right">@ak_iuran</td>\n')
  oFile.write('		<td width="10%" style="border-right:1px solid #000000; border-left-style:solid; border-left-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" bgcolor="#EFEFEF">\n')
  oFile.write('		<p align="right">@ak_pengalihan</td>\n')
  oFile.write('		<td width="10%" style="border-right:1px solid #000000; border-left-style:solid; border-left-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" bgcolor="#EFEFEF">\n')
  oFile.write('		@ak_pengembangan</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="70%" style="border-left:1px solid #000000; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" colspan="6" bgcolor="#CC6699">\n')
  oFile.write('		<b>TOTAL</b></td>\n')
  oFile.write('		<td width="10%" style="border-left:1px solid #000000; border-right-style:solid; border-right-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" bgcolor="#CC6699">\n')
  oFile.write('		<b>@TOT_AK_IURAN</b></td>\n')
  oFile.write('		<td width="10%" style="border-right:1px solid #000000; border-left-style:solid; border-left-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" bgcolor="#CC6699">\n')
  oFile.write('		<b>@TOT_AK_PENGALIHAN</b></td>\n')
  oFile.write('		<td width="10%" style="border-right:1px solid #000000; border-left-style:solid; border-left-width:1px; border-top-style:solid; border-top-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="right" bgcolor="#CC6699">\n')
  oFile.write('		<b>@TOT_AK_PENGEMB</b></td>\n')
  oFile.write('	</tr>\n')
  oFile.write('</table>\n')
  oFile.write('\n')
  oFile.write('\n')
  oFile.write('</body>\n')
  oFile.write('\n')
  oFile.write('</html>\n')
