  oFile.write('<html>\n')
  oFile.write('\n')
  oFile.write('<head>\n')
  oFile.write('<title>Statemen Individual</title>\n')
  oFile.write('</head>\n')
  oFile.write('\n')
  oFile.write('<body style="FONT-FAMILY: Arial; line-height:100%; margin-top:0; margin-bottom:0">\n')
  oFile.write('\n')
  oFile.write('<table border="1" width="100%" id="table1" style="border-width: 0px">\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td colspan="3" align="center" style="border-style: none; border-width: medium">\n')
  oFile.write('		REKENING KORAN</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">No. \n')
  oFile.write('		Peserta</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">:</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@no_peserta</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">Nama</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">:</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@nama</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">Alamat</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">:</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@alamat</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">&nbsp;</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">&nbsp;</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@kota @kodepos</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">Paket \n')
  oFile.write('		Investasi</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">:</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@paket \n')
  oFile.write('		investasi</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">Periode</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">:</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@dari_tanggal \n')
  oFile.write('		- @hingga_tanggal</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="19%" style="border-style: none; border-width: medium">Saldo \n')
  oFile.write('		Awal</td>\n')
  oFile.write('		<td width="2%" style="border-style: none; border-width: medium">:</td>\n')
  oFile.write('		<td width="76%" style="border-style: none; border-width: medium">@saldoawal</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('</table>\n')
  oFile.write('<table border="1" width="100%" id="table2" bordercolorlight="#000000" bordercolordark="#000000" style="border-collapse: collapse" bordercolor="#000000" cellpadding="2">\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="247" align="center" style="border-style: solid; border-width: 1px"><b>TANGGAL</b></td>\n')
  oFile.write('		<td width="95" align="center" style="border-style: solid; border-width: 1px"><b>MUTASI</b></td>\n')
  oFile.write('		<td width="90" align="center" style="border-style: solid; border-width: 1px"><b>SANDI</b></td>\n')
  oFile.write('		<td align="center" style="border-style: solid; border-width: 1px"><b>NOMINAL</b></td>\n')
  oFile.write('		<td align="center" style="border-style: solid; border-width: 1px"><b>SALDO</b></td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="247" align="center" style="border-style: solid; border-width: 1px">@tanggal</td>\n')
  oFile.write('		<td width="95" align="center" style="border-style: solid; border-width: 1px">@mutasi</td>\n')
  oFile.write('		<td width="90" align="center" style="border-style: solid; border-width: 1px">@sandi</td>\n')
  oFile.write('		<td align="right" style="border-style: solid; border-width: 1px">@nominal</td>\n')
  oFile.write('		<td align="right" style="border-style: solid; border-width: 1px">@saldo</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td width="247" style="border-style: solid; border-width: 1px">SALDO AKHIR</td>\n')
  oFile.write('		<td width="95" align="center" style="border-style: solid; border-width: 1px">&nbsp;</td>\n')
  oFile.write('		<td width="90" align="center" style="border-style: solid; border-width: 1px">&nbsp;</td>\n')
  oFile.write('		<td style="border-style: solid; border-width: 1px">&nbsp;</td>\n')
  oFile.write('		<td style="border-style: solid; border-width: 1px">\n')
  oFile.write('		<p align="right">@saldoakhir</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('</table>\n')
  oFile.write('<p>&nbsp;</p>\n')
  oFile.write('<table border="1" width="100%" id="table3" style="border-width: 0px; border-collapse:collapse" bordercolorlight="#000000" bordercolordark="#000000">\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td align="right" style="border-left-style: none; border-left-width: medium; border-right-style: none; border-right-width: medium; border-top-style: none; border-top-width: medium; border-bottom-style: solid; border-bottom-width: 1px">\n')
  oFile.write('		Dicetak tanggal @tanggal_cetak</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('	<tr>\n')
  oFile.write('		<td style="border-left-style: none; border-left-width: medium; border-right-style: none; border-right-width: medium; border-top-style: solid; border-top-width: 1px; border-bottom-style: none; border-bottom-width: medium">\n')
  oFile.write('		Keterangan Sandi</td>\n')
  oFile.write('	</tr>\n')
  oFile.write('</table>\n')
  oFile.write('\n')
  oFile.write('</body>\n')
  oFile.write('\n')
  oFile.write('</html>\n')
