--jangan lupa untuk sinkronisasi data master jenis transaksi DPLK

/* Creating table for class PengembalianDana */

CREATE TABLE PENGEMBALIANDANA(
  ID_TRANSAKSI INTEGER NOT NULL,
  ID_TRANSAKSI_BADMTHN INTEGER,
  ID_TRANSAKSI_BADMTRANS INTEGER,
  ID_TRANSAKSI_BPENG INTEGER,
  BIAYA_ADMINISTRASI DOUBLE PRECISION,
  BIAYA_PENCAIRAN DOUBLE PRECISION,
  BIAYA_PENGELOLAAN DOUBLE PRECISION,
  BIAYA_LAIN DOUBLE PRECISION,
  JENIS_BIAYA VARCHAR(1),
  COUNT_ADVIS INTEGER,
  SALDO_IURAN_PK DOUBLE PRECISION,
  SALDO_IURAN_PST DOUBLE PRECISION,
  SALDO_IURAN_TMB DOUBLE PRECISION,
  SALDO_PSL DOUBLE PRECISION,
  SALDO_PMB_PK DOUBLE PRECISION,
  SALDO_PMB_PST DOUBLE PRECISION,
  SALDO_PMB_TMB DOUBLE PRECISION,
  SALDO_PMB_PSL DOUBLE PRECISION,
  SALDO_JML_DANA DOUBLE PRECISION,
  PAJAK DOUBLE PRECISION,
  DANA_STLH_PAJAK DOUBLE PRECISION,
  DANA_DIKEMBALIKAN DOUBLE PRECISION,
PRIMARY KEY (ID_TRANSAKSI)
);

insert into enum_varchar values ('eJenisTransaksiDPLK','Q','Pengembalian Dana');