update TRANSAKSIDPLK
set TRANSAKSIDPLK.KODE_JENIS_TRANSAKSI = 'V'
from TRANSAKSIDPLK, PENARIKANDANA
where TRANSAKSIDPLK.KODE_JENIS_TRANSAKSI = 'E' and
      TRANSAKSIDPLK.ID_Transaksi = PENARIKANDANA.ID_Transaksi and
      PENARIKANDANA.penarikan_phk = 'F';
      
update TRANSAKSIDPLK
set TRANSAKSIDPLK.KODE_JENIS_TRANSAKSI = 'W'
from TRANSAKSIDPLK, PENARIKANDANA
where TRANSAKSIDPLK.KODE_JENIS_TRANSAKSI = 'E' and
      TRANSAKSIDPLK.ID_Transaksi = PENARIKANDANA.ID_Transaksi and
      PENARIKANDANA.penarikan_phk = 'T';
