/* Creating table for class Investasi */

CREATE TABLE INVESTASI(
  ID_INVESTASI INTEGER NOT NULL,
  NO_BILYET VARCHAR(15),
  AKUM_NOMINAL DOUBLE PRECISION,
  AKUM_PIUTANGLR DOUBLE PRECISION,
  AKUM_LR DOUBLE PRECISION,
  STATUS VARCHAR(1),
  TGL_BUKA DATETIME,
  TGL_TUTUP DATETIME,
  ROLLOVER_COUNTER INTEGER,
  USER_ID VARCHAR(20),
  LAST_UPDATE DATETIME,
  TERMINAL_ID VARCHAR(15),
  USER_ID_AUTH VARCHAR(20),
  TERMINAL_ID_AUTH VARCHAR(15),
  TGL_OTORISASI DATETIME,
  NOMINAL_PEMBUKAAN DOUBLE PRECISION,
  KODE_PIHAK_KETIGA VARCHAR(8),
  KODE_PAKET_INVESTASI VARCHAR(2),
  KODE_JNS_INVESTASI VARCHAR(3),
PRIMARY KEY (ID_INVESTASI)
);

/* Creating table for class JenisInvestasi */

CREATE TABLE JENISINVESTASI(
  KODE_JNS_INVESTASI VARCHAR(3) NOT NULL,
  NAMA_JNS_INVESTASI VARCHAR(20),
  expected_rate DOUBLE PRECISION,
  acc_investasi VARCHAR(20),
  acc_pendapatan VARCHAR(20),
  acc_biayainvest VARCHAR(20),
  acc_piutangpendapatan VARCHAR(20),
  acc_potensi_profit VARCHAR(20),
  USER_ID VARCHAR(20),
  LAST_UPDATE DATETIME,
PRIMARY KEY (KODE_JNS_INVESTASI)
);

/* Creating table for class JnsTransInvestasi */

CREATE TABLE JNSTRANSINVESTASI(
  KODE_JENIS_TRINVESTASI VARCHAR(1) NOT NULL,
  DESKRIPSI VARCHAR(100),
  USER_ID VARCHAR(20),
  LAST_UPDATE DATETIME,
PRIMARY KEY (KODE_JENIS_TRINVESTASI)
);

/* Altering table for class PaketInvestasi */

ALTER TABLE PAKETINVESTASI
  ADD total_potensi_profit DOUBLE PRECISION,
  acc_giro VARCHAR(20),
  acc_iuran VARCHAR(20),
  acc_peralihan VARCHAR(20),
  acc_pengembangan VARCHAR(20),
  acc_kedplklain VARCHAR(20),
  acc_manfaat VARCHAR(20);

/* Creating table for class PihakKetiga */

CREATE TABLE PIHAKKETIGA(
  kode_pihak_ketiga VARCHAR(8) NOT NULL,
  nama_pihak_ketiga VARCHAR(30),
  ALAMAT_PIHAK_KETIGA VARCHAR(50),
  SELF_INVESTMENT VARCHAR(1),
  USER_ID VARCHAR(20),
  LAST_UPDATE DATETIME,
PRIMARY KEY (kode_pihak_ketiga)
);

/* Creating table for class RegisterInvestasi */

CREATE TABLE REGISTERINVESTASI(
  ID_REGISTERINVESTASI INTEGER NOT NULL,
  NO_BILYET VARCHAR(15),
  TGL_BUKA DATETIME,
  USER_ID VARCHAR(20),
  TERMINAL_ID VARCHAR(15),
  TANGGAL_REGISTER DATETIME,
  NOMINAL DOUBLE PRECISION,
  KODE_PIHAK_KETIGA VARCHAR(8),
  KODE_PAKET_INVESTASI VARCHAR(2),
  KODE_JNS_INVESTASI VARCHAR(3),
  ID_TRANSACTIONBATCH INTEGER,
PRIMARY KEY (ID_REGISTERINVESTASI)
);

/* DROPPING TABLE FOR RincianPaketInvestasi */

DROP TABLE RINCIANPAKETINVESTASI;

/* Creating table for class RincianPaketInvestasi */

CREATE TABLE RINCIANPAKETINVESTASI(
  kode_paket_investasi VARCHAR(2) NOT NULL,
  maks_proporsi DOUBLE PRECISION,
  total_dana_alokasi DOUBLE PRECISION,
  total_hasil_pengembangan DOUBLE PRECISION,
  hasil_pengembangan_dibagikan DOUBLE PRECISION,
  total_potensi_profit DOUBLE PRECISION,
  KODE_JNS_INVESTASI VARCHAR(3) NOT NULL,
PRIMARY KEY (kode_paket_investasi, KODE_JNS_INVESTASI)
);

/* Creating table for class SubJnsTransLRInvestasi */

CREATE TABLE SUBJNSTRANSLRINVESTASI(
  KODE_SUBJNS_LRINVESTASI VARCHAR(20) NOT NULL,
  KATEGORI VARCHAR(1),
  DESKRIPSI VARCHAR(100),
  ACCOUNT_CODE VARCHAR(20),
  USER_ID VARCHAR(20),
  LAST_UPDATE DATETIME,
  KODE_JNS_INVESTASI VARCHAR(3),
PRIMARY KEY (KODE_SUBJNS_LRINVESTASI)
);

/* Creating table for class TransaksiInvestasi */

CREATE TABLE TRANSAKSIINVESTASI(
  ID_TRANSAKSIINVESTASI INTEGER NOT NULL,
  TGL_TRANSAKSI DATETIME,
  MUTASI_DEBET DOUBLE PRECISION,
  MUTASI_KREDIT DOUBLE PRECISION,
  USER_ID VARCHAR(20),
  USER_ID_AUTH VARCHAR(20),
  TERMINAL_ID VARCHAR(15),
  TERMINAL_ID_AUTH VARCHAR(15),
  TGL_OTORISASI DATETIME,
  TGL_SISTEM DATETIME,
  ISCOMMITTED VARCHAR(1),
  KODE_JENIS_TRINVESTASI VARCHAR(20),
  CLSFTRANSAKSIINVESTASI VARCHAR(1),
  NO_BILYET VARCHAR(15),
  ID_TRANSACTIONBATCH INTEGER,
PRIMARY KEY (ID_TRANSAKSIINVESTASI)
);

/* Creating table for class TransLRInvestasi */

CREATE TABLE TRANSLRINVESTASI(
  ID_TRANSAKSIINVESTASI INTEGER NOT NULL,
  ID_INVESTASI INTEGER,
  KODE_SUBJNS_LRINVESTASI VARCHAR(20),
PRIMARY KEY (ID_TRANSAKSIINVESTASI)
);

/* Creating table for class TransPiutangInvestasi */

CREATE TABLE TRANSPIUTANGINVESTASI(
  ID_TRANSAKSIINVESTASI INTEGER NOT NULL,
  ID_INVESTASI INTEGER,
PRIMARY KEY (ID_TRANSAKSIINVESTASI)
);

/* Creating table for class TransPiutangLRInvestasi */

CREATE TABLE TRANSPIUTANGLRINVESTASI(
  ID_TRANSAKSIINVESTASI INTEGER NOT NULL,
  ID_TRANSAKSIINVESTASI_PIUTINV INTEGER,
  ID_TRANSAKSIINVESTASI_LRINV INTEGER,
  ID_INVESTASI INTEGER,
PRIMARY KEY (ID_TRANSAKSIINVESTASI)
);