/* Altering table for class IuranPendaftaran */

ALTER TABLE IURANPENDAFTARAN
  ADD MUTASI_IURAN DOUBLE PRECISION;

/* Creating table for class Parameter */

CREATE TABLE PARAMETER(
  KEY_PARAMETER VARCHAR(20) NOT NULL,
  NUMERIC_VALUE DOUBLE PRECISION,
  VARCHAR_VALUE VARCHAR,
PRIMARY KEY (KEY_PARAMETER)
);

/* Altering table for class TransactionBatch */

ALTER TABLE TRANSACTIONBATCH
  ADD JAM_MULAI_PAKAI DATETIME,
  JAM_AKHIR_PAKAI DATETIME;

/* Altering table for class UserApp */

ALTER TABLE USERAPP
  ADD USER_TIMEZONE INTEGER;