-- Script generated by WinSQL on 28/06/2007 11:52:37
-- 
INSERT INTO "dbo"."JENISPENERIMAANMANFAAT"("kode_jns_manfaat", "nama_jns_manfaat", "LAST_UPDATE", "USER_ID")
VALUES ('B', 'Pensiun Biasa', '2007-06-14 12:16:51.000', 'root')
GO

INSERT INTO "dbo"."JENISPENERIMAANMANFAAT"("kode_jns_manfaat", "nama_jns_manfaat", "LAST_UPDATE", "USER_ID")
VALUES ('C', 'Pensiun Cacat', '2007-06-14 12:17:27.000', 'root')
GO

INSERT INTO "dbo"."JENISPENERIMAANMANFAAT"("kode_jns_manfaat", "nama_jns_manfaat", "LAST_UPDATE", "USER_ID")
VALUES ('D', 'Pensiun Dipercepat', '2007-06-14 12:17:16.000', 'root')
GO

INSERT INTO "dbo"."JENISPENERIMAANMANFAAT"("kode_jns_manfaat", "nama_jns_manfaat", "LAST_UPDATE", "USER_ID")
VALUES ('J', 'Pensiun Janda / Anak', '2007-06-14 12:17:38.000', 'root')
GO

-- Total records processed: 4

-- Script generated by WinSQL on 28/06/2007 11:52:38
-- 
INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('A', 'Register Pindah Alamat', 'root', '2007-05-16 16:05:39.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('D', 'Register Ubah Status AutoDebet', 'admin', '2007-06-25 16:24:17.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('I', 'Register Ubah Iuran', 'admin', '2007-06-25 16:23:27.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('K', 'Register Ubah Status Kerja', 'root', '2007-05-16 16:05:46.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('N', 'Register Ubah Anuitas', 'admin', '2007-06-25 16:23:44.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('P', 'Register Ubah Paket Investasi', 'admin', '2007-06-25 16:23:09.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('U', 'Register Ubah Wasiat Ummat', 'admin', '2007-06-25 16:22:44.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('W', 'Register Ubah Ahli Waris', 'admin', '2007-06-25 16:22:25.000')
GO

INSERT INTO "dbo"."JENISREGISTERCIF"("KODE_JENIS_REGISTERCIF", "NAMA_JENIS_REGISTERCIF", "USER_ID", "LAST_UPDATE")
VALUES ('Z', 'Register Lain-lain', 'admin', '2007-06-25 16:24:43.000')
GO

-- Total records processed: 9

-- Script generated by WinSQL on 28/06/2007 11:52:38
-- 
INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('A', 'Pendaftaran', 100, '2007-05-16 14:54:27.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('B', 'Pembayaran Premi', 100, '2007-06-06 12:21:55.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('C', 'Biaya Pengelolaan Dana', 100, '2007-06-26 18:45:02.000', 'admin')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('D', 'Biaya Administrasi Tahunan', 100, '2007-06-25 16:15:45.000', 'admin')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('H', 'Pengalihan ke DPLK Lain', 100, '2007-06-06 12:22:35.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('I', 'Pengalihan dari DPLK lain', 100, '2007-06-06 12:23:03.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('J', 'Pengambilan Manfaat', 100, '2007-06-06 12:23:44.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('K', 'Iuran Peserta', 100, '2007-06-06 12:26:34.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('M', 'Transaksi DPLK Manual', 100, '2007-06-06 12:27:33.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('V', 'Penarikan Dana 30%', 100, '2007-06-06 12:26:00.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('W', 'Penarikan Dana PHK', 100, '2007-06-06 12:26:17.000', 'root')
GO

INSERT INTO "dbo"."JENISTRANSAKSIDPLK"("kode_jenis_transaksi", "nama_transaksi", "BACKDATE_DAYS", "LAST_UPDATE", "USER_ID")
VALUES ('X', 'Biaya Administrasi Transaksi', 100, '2007-06-25 16:15:50.000', 'admin')
GO

-- Total records processed: 12

-- Script generated by WinSQL on 28/06/2007 11:52:38
-- 
INSERT INTO "dbo"."OPERATIONCODE"("OPERATION_CODE", "KETERANGAN", "USER_ID", "LAST_UPDATE", "OPERATION_NAME")
VALUES ('E', 'Operasi yang sedang / telah diedit', 'admin', '2007-06-25 16:21:07.000', 'Edit')
GO

INSERT INTO "dbo"."OPERATIONCODE"("OPERATION_CODE", "KETERANGAN", "USER_ID", "LAST_UPDATE", "OPERATION_NAME")
VALUES ('F', 'Operasi yang sudah commit', 'admin', '2007-06-25 16:20:15.000', 'Free')
GO

INSERT INTO "dbo"."OPERATIONCODE"("OPERATION_CODE", "KETERANGAN", "USER_ID", "LAST_UPDATE", "OPERATION_NAME")
VALUES ('N', 'Operasi yang akan di-commit', 'admin', '2007-06-25 16:20:47.000', 'New')
GO

-- Total records processed: 3

-- Script generated by WinSQL on 29/06/2007 15:49:34
--
INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BATAS_MANFAAT_KENA_ANUITAS', 100000000.0, null, 'Batas nominal Rp Manfaat cair yang terkena Anuitas')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BATAS_WAKTU_PENARIKAN_NORMAL', 183.0, null, 'Jumlah hari yang menjadi batas waktu penarikan')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BESAR_BIAYA_DAFTAR', 20000.0, null, 'Rp biaya pendaftaran peserta DPLK')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BIAYA_ADM_TAHUNAN', 5000.0, null, 'Rp biaya administrasi tahunan')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BIAYA_RTGS', 30000.0, null, 'Rp biaya Real Time Gross Sentlement Bank Indonesia')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BIAYA_SKN', 5000.0, null, 'Rp biaya Sistem Kliring Nasional')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('BIAYA_TUNAI', 5000.0, null, 'Rp biaya pengeluaran buku cek untuk giro')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('JUMLAH_HARI_SETAHUN', 365.0, null, 'Jumlah hari dalam 1 tahun')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('MIN_JML_AKUM_IURAN_PST', 1500000.0, null, 'Min Rp Akum Dana Iuran Peserta yg boleh ditarik')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_BATAS_TUNAI_MANFAAT', 20.0, null, '% Manfaat Pensiun yang bisa ditarik tunai')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_BIAYA_PENGELOLAAN', 1.0, null, '% biaya pengelolaan')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_BIAYA_PINDAH_DPLK', 1.0, null, '% biaya pindah Pengalihan Dana ke DPLK lain')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_BIAYA_PINDAH_INVESTASI', 1.0, null, '% biaya transaksi saat pindah Paket Investasi')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_BIAYA_TARIK_NORMAL', 1.0, null, '% biaya tarik untuk Penarikan Dana Normal 30%')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_BIAYA_TARIK_PHK', 2.5, null, '% biaya tarik untuk Penarikan Dana PHK')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_CAIR_MANFAAT_<1TH', 2.5, null, '% biaya pencairan Pengambilan Manfaat < 1 th')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_CAIR_MANFAAT_>=1TH', 1.0, null, '% biaya pencairan Pengambilan Manfaat >= 1 th')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PERSEN_PENARIKAN_NORMAL', 30.0, null, 'Batas Rp penarikan dana normal 30% oleh nasabah')
GO

INSERT INTO "PARAMETER"("KEY_PARAMETER", "NUMERIC_VALUE", "VARCHAR_VALUE", "DESCRIPTION")
VALUES ('PRESISI_ANGKA_FLOAT', 9.9999999999999995E-8, null, 'Presisi angka untuk komparasi bilangan float')
GO

-- Total records processed: 19