/* Altering table for class HistoriSRR */

ALTER TABLE HISTORISRR
  ADD ID_SRRCALCRINCIAN INTEGER;

/* Altering table for class SRRCalcBagiHasil */

ALTER TABLE SRRCALCBAGIHASIL
  ADD ID_SRRCALCRINCIAN INTEGER;

/* Creating table for class SRRCalcRincian */

CREATE TABLE SRRCALCRINCIAN(
  KODE_PAKET_INVESTASI VARCHAR(2),
  TOTAL_SRR DOUBLE PRECISION,
  ID_SRRCALCRINCIAN INTEGER NOT NULL,
  ID_SRRCALC INTEGER,
PRIMARY KEY (ID_SRRCALCRINCIAN)
);