/* JALANKAN SQL INI SETELAH MELAKUKAN PERHITUNGAN SRR PERDANA */
/* PERHITUNGAN SRR PERDANA ADALAH PERHITUNGAN SRR YANG DILAKUKAN PERTAMA KALI */
/* PERHITUNGAN SRR PERDANA MELIPUTI TANGGAL AWAL SEJAK PERTAMA KALI ADA TRANSAKSI (1 JANUARI 2006 */
/* HINGGA TANGGAL AKHIR YAITU BAGI HASIL TERAKHIR DI DPLK LAMA (31 MARET 2008) */

DELETE FROM SRRCalcRincian
WHERE ID_SRRCalc in
  (SELECT ID_SRRCalc
  FROM SRRCalc
  WHERE Tgl_Akhir_Hitung = '2008-03-31'
    and Tgl_Mulai_Hitung = '2006-01-01');

DELETE FROM SRRCalc
WHERE Tgl_Akhir_Hitung = '2008-03-31'
  and Tgl_Mulai_Hitung = '2006-01-01';
